export const data={
    "Vinh's task": {
        "1": [
            {
                "id": 74,
                "title": "MA: Line mobile change payment method",
                "content": "create new screen",
                "link": null,
                "type": "Vinh's task",
                "progress": null,
                "dueDate": "2025-08-14",
                "isMainTask": false,
                "status": "1",
                "mainTaskId": 60,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 68,
                "title": "select phone number screen",
                "content": "after login, if dont choose any phone number and press ok, will be force log out",
                "link": null,
                "type": "Vinh's task",
                "progress": null,
                "dueDate": "2025-08-01",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 66,
                "title": "Fix vietnamese in mnp transfer",
                "content": "https://gtn.backlog.com/view/GTNMOBILE-119#comment-233809800",
                "link": null,
                "type": "Vinh's task",
                "progress": null,
                "dueDate": "2025-08-06",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": "null"
            },
            {
                "id": 63,
                "title": "Analyze epos banner base on firebase event",
                "content": "Vinh san:\n- Possible, but need to research about firebase event\n- Send time to event then use big query to analyze\n- Use firebase event to track but there is no charge\nEst: 1.5->2\n\n- Display base on condition:\n- Show on change payment method\n\nResearch big query + looker studio\n",
                "link": null,
                "type": "Vinh's task",
                "progress": null,
                "dueDate": "2025-08-07",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": "null"
            },
            {
                "id": 61,
                "title": "update dialog for app",
                "content": "with not force update, create screen to notify user",
                "link": null,
                "type": "Vinh's task",
                "progress": null,
                "dueDate": "2025-07-31",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 52,
                "title": "MA: error message in birthday campagin",
                "content": "need more message detail",
                "link": null,
                "type": "Vinh's task",
                "progress": null,
                "dueDate": "2025-06-19",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            }
        ],
        "3": [
            {
                "id": 30,
                "title": ",MA: upload reissue sim image",
                "content": "https://gtn.backlog.com/view/MOBILE_0-300",
                "link": null,
                "type": "Vinh's task",
                "progress": 50,
                "dueDate": "2025-06-28",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 33,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 58,
                "title": ".ストアポリシの修正",
                "content": ".",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-07-02",
                "isMainTask": false,
                "status": "3",
                "mainTaskId": 59,
                "reportGroupId": 1,
                "reportStatus": "0"
            },
            {
                "id": 37,
                "title": ".Bug: モバイアプリ　UI ",
                "content": "STGテスト待ち\n対応済\n1. べトナム語が間違い表示してます\nhttps://gtn.backlog.com/view/MOBILE_0-297\n\n2. ビザ期限が表示してない\nhttps://gtn.backlog.com/view/MOBILE_0-295\n\n3.ダークモードでテキストを表示してない\nhttps://gtn.backlog.com/view/MOBILE_0-296\n\n4.モバイルアプリの支払い方法変更時の画面改修\n https://gtn.backlog.com/view/GTNMOBILE-102#comment-226032699\n\n\n\n\n",
                "link": null,
                "type": "Vinh's task",
                "progress": null,
                "dueDate": "2025-06-03",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 46,
                "title": "bug: reconnect",
                "content": "tmp",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-06-03",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 37,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 44,
                "title": "MA: reset password ",
                "content": "https://gtn.backlog.com/view/MOBILE_0-308",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-06-03",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 43,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 28,
                "title": ",MA: change payment method",
                "content": "https://gtn.backlog.com/view/MOBILE_0-290",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-06-28",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 7,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 50,
                "title": "MA: の支払い方法変更時のメッセージ",
                "content": "https://gtn.backlog.com/view/GTNMOBILE-102#comment-226032699",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-06-04",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": 37,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 42,
                "title": ",MA: rakuten",
                "content": "https://gtn.backlog.com/view/MOBILE_0-294",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-06-03",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 29,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 31,
                "title": ",MA: Reissue sim duplicated",
                "content": "\nhttps://gtn.backlog.com/view/MOBILE_0-302",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-05-30",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 36,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 47,
                "title": "bug: error when render",
                "content": "https://gtn-corporate.slack.com/archives/C08H8P833C4/p1748931726996759",
                "link": null,
                "type": "Vinh's task",
                "progress": 100,
                "dueDate": "2025-06-03",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 37,
                "reportGroupId": 1,
                "reportStatus": "null"
            }
        ]
    },
    "Personal tasks": {
        "1": [
            {
                "id": 72,
                "title": "APN in surport page",
                "content": "APN in surport page",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-08-13",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 70,
                "title": "create app account imediately for app",
                "content": "create app account imediately for app",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-08-12",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 69,
                "title": "prepaid app or screen",
                "content": "create prepaid screen or app",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-08-12",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 64,
                "title": "send notification in IOS",
                "content": "Can send notifcation in「Do Not Disturb」\n-> need to research",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-08-01",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 49,
                "title": "refactor",
                "content": "https://gtn.backlog.com/view/MOBILE_0-289\nrefactor\nget/payments : response not count\ndont use , use profile.nationality instead userIdentificationAdminApiClient.getUserNationalityByGtnId\nhttps://gtn.backlog.com/view/MOBILE_0-309\nChange credit usecase: line 40 k cần check production\nupgradge package",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-06-04",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": "null"
            },
            {
                "id": 19,
                "title": "cant use app when status = cancel",
                "content": "cant use app when status = cancel, 解約, \nfindBySimNumberAndProfileId\ndelete sim the delete  profile if dont have relation",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-17",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 23,
                "title": "birthday is future",
                "content": "dont understant, Talash 話",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-16",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 22,
                "title": "Trigger when have happinessId ",
                "content": "Trigger when have happinessId ",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-17",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            },
            {
                "id": 4,
                "title": "research sync sf to db",
                "content": "2-way sync from sf to db",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-06",
                "isMainTask": null,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": null
            }
        ],
        "2": [
            {
                "id": 60,
                "title": "Line Mobileのような支払い変更画面",
                "content": "API調査済、\nMAのリソース待ち",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-07-16",
                "isMainTask": true,
                "status": "2",
                "mainTaskId": null,
                "reportGroupId": 1,
                "reportStatus": "2"
            },
            {
                "id": 71,
                "title": "HappinessIdからServiceIdまでの変更",
                "content": "ローカル：テスト中\nStaging：テスト待ち",
                "link": null,
                "type": "Personal tasks",
                "progress": 60,
                "dueDate": "2025-08-13",
                "isMainTask": true,
                "status": "2",
                "mainTaskId": null,
                "reportGroupId": 1,
                "reportStatus": "2"
            }
        ],
        "3": [
            {
                "id": 65,
                "title": "add plan to submonth",
                "content": "need to create backlog ",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-08-01",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": "null"
            },
            {
                "id": 10,
                "title": ".Ymobile データチャージ",
                "content": "再開発完了\nローカル：テスト中\nStaging：テスト待ち\nhttps://gtn.backlog.com/view/MOBILE_0-287\n",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-07",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 1,
                "reportStatus": "2"
            },
            {
                "id": 62,
                "title": "ダイアルの利用促進",
                "content": "https://gtn.backlog.com/view/MOBILE_0-318",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-07-25",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 1,
                "title": "Import STG database from SF",
                "content": "Import STG database from SF\n",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-05",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": "null"
            },
            {
                "id": 59,
                "title": "最新アプリリリース",
                "content": "version 1.5.6+252",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-07-16",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 33,
                "title": " .シム再発行、身分証明証アップロード",
                "content": "開発完了\nhttps://gtn.backlog.com/view/MOBILE_0-298",
                "link": null,
                "type": "Personal tasks",
                "progress": 100,
                "dueDate": "2025-06-06",
                "isMainTask": false,
                "status": "3",
                "mainTaskId": 59,
                "reportGroupId": 1,
                "reportStatus": "0"
            },
            {
                "id": 29,
                "title": ".モバイルアプリで楽天のデータ使用量を表示",
                "content": "https://gtn.backlog.com/view/MOBILE_0-291",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-06-28",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 7,
                "title": ".支払い方法変更の改修",
                "content": "https://gtn.backlog.com/view/MOBILE_0-284",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-16",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 36,
                "title": ".シム再発行、重複防止",
                "content": "STGテスト待ち\nシム再発行、重複防止",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-06-06",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 9,
                "title": "ps:no need-update bill_url into sf",
                "content": "情報待ち\ndont have 許可ID, 許可パスワード",
                "link": null,
                "type": "Personal tasks",
                "progress": null,
                "dueDate": "2025-05-08",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "4"
            }
        ]
    },
    "Thang's tasks": {
        "1": [
            {
                "id": 54,
                "title": "HappinessIdからServiceIdの使用に変更しました。",
                "content": "https://gtn.backlog.com/view/MOBILE_0-311",
                "link": null,
                "type": "Thang's tasks",
                "progress": null,
                "dueDate": "2025-07-18",
                "isMainTask": true,
                "status": "1",
                "mainTaskId": null,
                "reportGroupId": 1,
                "reportStatus": "null"
            }
        ],
        "2": [
            {
                "id": 73,
                "title": "BE: Line mobile change payment method",
                "content": "開発中",
                "link": null,
                "type": "Thang's tasks",
                "progress": 10,
                "dueDate": "2025-08-14",
                "isMainTask": null,
                "status": "2",
                "mainTaskId": 60,
                "reportGroupId": 1,
                "reportStatus": "null"
            }
        ],
        "3": [
            {
                "id": 57,
                "title": "初月の一日にYM/SB通話料の更新",
                "content": "開発完了、本番反映済\nhttps://gtn.backlog.com/view/MOBILE_0-315",
                "link": null,
                "type": "Thang's tasks",
                "progress": null,
                "dueDate": "2025-07-02",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 40,
                "title": ",BE: Reissue sim, upload identity",
                "content": "https://gtn.backlog.com/view/MOBILE_0-301\n",
                "link": null,
                "type": "Thang's tasks",
                "progress": 90,
                "dueDate": "2025-06-03",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 33,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 48,
                "title": ".誕生キャンペーンがSlackに送信",
                "content": "応募者数がSlackに送信\n\nhttps://gtn.backlog.com/view/MOBILE_0-304",
                "link": null,
                "type": "Thang's tasks",
                "progress": null,
                "dueDate": "2025-06-04",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "2"
            },
            {
                "id": 35,
                "title": "-fix: other data charge api",
                "content": "https://gtn.backlog.com/view/MOBILE_0-304",
                "link": null,
                "type": "Thang's tasks",
                "progress": null,
                "dueDate": "2025-06-02",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": null,
                "reportStatus": "3"
            },
            {
                "id": 56,
                "title": "ネパール語で解約できない",
                "content": "https://gtn.backlog.com/view/MOBILE_0-316",
                "link": null,
                "type": "Thang's tasks",
                "progress": 100,
                "dueDate": "2025-07-02",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 13,
                "title": ",BE: reset password",
                "content": "https://gtn.backlog.com/view/MOBILE_0-288",
                "link": null,
                "type": "Thang's tasks",
                "progress": 100,
                "dueDate": "2025-05-09",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 43,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 51,
                "title": "fix email translation",
                "content": "https://gtn.backlog.com/add/MOBILE_0",
                "link": null,
                "type": "Thang's tasks",
                "progress": null,
                "dueDate": "2025-06-19",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 24,
                "title": ".誕生キャンペーンがSlackに送信",
                "content": "対象者数、当選者Slackに送信\n１日、8日、15日、22日\n\nhttps://gtn.backlog.com/view/MOBILE_0-285",
                "link": null,
                "type": "Thang's tasks",
                "progress": null,
                "dueDate": "2025-05-08",
                "isMainTask": true,
                "status": "3",
                "mainTaskId": null,
                "reportGroupId": 10,
                "reportStatus": "0"
            },
            {
                "id": 41,
                "title": ",BE: rakuten",
                "content": "https://gtn.backlog.com/view/MOBILE_0-289",
                "link": null,
                "type": "Thang's tasks",
                "progress": 100,
                "dueDate": "2025-06-03",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 29,
                "reportGroupId": 1,
                "reportStatus": "null"
            },
            {
                "id": 14,
                "title": ",BE : Reissue sim duplicated",
                "content": "https://gtn.backlog.com/view/MOBILE_0-281 \n",
                "link": null,
                "type": "Thang's tasks",
                "progress": 100,
                "dueDate": "2025-05-06",
                "isMainTask": null,
                "status": "3",
                "mainTaskId": 36,
                "reportGroupId": 1,
                "reportStatus": "0"
            }
        ]
    }
}